{"uuid":"0e50fa1f-0206-41b8-9080-0204da626649","historyId":"ec9bd582074977ae79271d203e632dee","fullName":"com.testNG.InvacationCountTest.loginTest","labels":[{"name":"package","value":"com.testNG.InvacationCountTest"},{"name":"testClass","value":"com.testNG.InvacationCountTest"},{"name":"testMethod","value":"loginTest"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"VWOLoginAutomationSeleniumTestNG"},{"name":"subSuite","value":"com.testNG.InvacationCountTest"},{"name":"host","value":"Satyam"},{"name":"thread","value":"29676@Satyam.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"loginTest","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"\nExpected exception of type class java.lang.NumberFormatException but got org.testng.internal.thread.ThreadTimeoutException: Method com.testNG.InvacationCountTest.loginTest() didn't finish within the time-out 2","trace":"org.testng.TestException: \nExpected exception of type class java.lang.NumberFormatException but got org.testng.internal.thread.ThreadTimeoutException: Method com.testNG.InvacationCountTest.loginTest() didn't finish within the time-out 2\r\n\tat org.testng.internal.invokers.ExpectedExceptionsHolder.wrongException(ExpectedExceptionsHolder.java:67)\r\n\tat org.testng.internal.invokers.TestInvoker.considerExceptionsInternal(TestInvoker.java:885)\r\n\tat org.testng.internal.invokers.TestInvoker.considerExceptions(TestInvoker.java:860)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:741)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:739)\r\n\tat org.testng.TestRunner.run(TestRunner.java:614)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:421)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:312)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1208)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1112)\r\n\tat org.testng.TestNG.run(TestNG.java:1079)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\nCaused by: org.testng.internal.thread.ThreadTimeoutException: Method com.testNG.InvacationCountTest.loginTest() didn't finish within the time-out 2\r\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1756451137859,"stop":1756451137902}